# Core config
esphome:
  name: lightstick
  includes:
    - loona_colors.h
    - hsv2rgb.h
    - rainbow_effect.h
  on_boot:
    then:
      - lambda: |-
          go_to_next_color();

esp32:
  board: esp32dev

external_components:
  - source: components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lightstick"
    password: "dalsodalsogaja"

# Variables
globals:
  - id: current_member
    type: int
    initial_value: '0'

# Light
light:
  - platform: rgbw
    name: "LOOΠΔ Light Stick"
    id: leds
    red: led_red
    green: led_green
    blue: led_blue
    white: led_white
    effects: !include effects.yaml

output:
  - platform: ledc
    id: led_red
    pin: GPIO17
    max_power: 80%
  - platform: ledc
    id: led_green
    pin: GPIO18
    max_power: 80%
  - platform: ledc
    id: led_blue
    pin: GPIO19
    max_power: 80%
  - platform: ledc
    id: led_white
    pin: GPIO21
    max_power: 80%

# Button
binary_sensor:
  - platform: gpio
    id: button
    internal: true
    pin: &button
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.3s
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - logger.log:
              format: "Starting rainbow effect"
              level: INFO
              tag: click
          - light.turn_on:
              id: leds
              effect: Fast Rainbow
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - lambda: |-
              go_to_next_color();
      - timing:
          - ON for at least 1s
        then:
          - logger.log:
              format: "Entering deep sleep"
              level: INFO
              tag: click
          - light.turn_off:
              id: leds
          - deep_sleep.enter:
              id: poweroff

# Deep Sleep
deep_sleep:
  id: poweroff
  wakeup_pin: *button
  wakeup_pin_mode: KEEP_AWAKE

# Bluetooth
esp32_ble:

esp32_ble_server:
  manufacturer: Maxr1998
  model: HighBong v2

esp32_ble_lightstick:
  light: leds

# Misc
api:

web_server:
  port: 80
  include_internal: true

logger:
  level: INFO

ota:
  password: !secret ota_password
  num_attempts: 3
